In [1]:
import numpy as np

Generate a random 10 by 10 matrix with random integers chosen from [1,1000]

array([[683, 825, 680,  45, 152, 168,  93, 188, 512, 980],
       [286, 926, 339, 940, 424,  30, 166, 960, 454, 762],
       [730, 353, 884, 483,  15, 252, 548, 777, 546, 595],
       [513, 861, 805, 702, 803,  49, 990, 625, 555, 876],
       [393,  17, 571, 316, 274, 169, 372, 940, 492, 646],
       [320, 872, 440,  89, 217, 583, 296, 656, 391, 615],
       [125, 802, 344, 233, 420,  71, 844, 410, 988, 894],
       [238, 455, 972, 319, 861, 454, 382, 217, 373, 491],
       [202,  20, 542, 204, 367, 863, 486, 857, 359, 313],
       [156, 848, 834, 887, 204, 422, 132, 640, 257, 575]])

Use fancy indexing to return data located on the 2nd, 4th, 6th, and 8th column. The result should be a 10 by 4 matrix

array([[825,  45, 168, 188],
       [926, 940,  30, 960],
       [353, 483, 252, 777],
       [861, 702,  49, 625],
       [ 17, 316, 169, 940],
       [872,  89, 583, 656],
       [802, 233,  71, 410],
       [455, 319, 454, 217],
       [ 20, 204, 863, 857],
       [848, 887, 422, 640]])

Use the 10 by 4 matrix received above to get its first row and then make it a column vector (size is 4 by 1)

(4, 1)

Get the second row of the matrix and make it a 1 by 4 row vector

(1, 4)

Multiple both vectors into a 4 by 4 matrix

array([[763950, 775500,  24750, 792000],
       [ 41670,  42300,   1350,  43200],
       [155568, 157920,   5040, 161280],
       [174088, 176720,   5640, 180480]])

Suppose the following dictionary saves the information about the data submission with respect to the original 10 by 10 matrix: {‘Bob’:[0,3,7],’Alice’:[2,4,8],’Caro’:[1,9],’Dave’:[5,6]}. For example, Bob submitted the 1st, 4th, and 8th rows and Caro submitted the 2nd and 10th rows. Calculate the following items:

a.	The mean of data submitted by Bob and Caro together

522.18

b.	The column-wise average of data submitted by Alice

array([441.66666667, 130.        , 665.66666667, 334.33333333,
       218.66666667, 428.        , 468.66666667, 858.        ,
       465.66666667, 518.        ])

c.	Data from Dave where they are greater than 500, if any

array([872, 583, 656, 615, 802, 844, 988, 894])

d.	The row-wise standard deviation of data submitted by Caro and Dave

array([325.44555612, 285.2999299 , 222.30539805, 321.86874654])

e.	Data from Bob where they are greater than their element-wise counterpart from Alice, if any

array([[  0, 825,   0,   0, 152,   0,   0,   0,   0, 980],
       [513, 861, 805, 702, 803,   0, 990,   0, 555, 876],
       [238, 455, 972, 319, 861,   0,   0,   0, 373, 491]])